/**
 * Skill tree node definitions extracted into a dedicated module.
 * Provides `perkNodes` on the global scope for the main graph script.
 */
(function (global) {
  const nodes = {
    languages: [
      {
        key: "languages-1",
        icon: "images/logo-python.png",
        prof: 3,
        unlocked: true,
        alt: "Python Fundamentals",
      },
      {
        key: "languages-2",
        icon: "images/logo-javascript.png",
        prof: 4,
        unlocked: true,
        alt: "JavaScript Fundamentals",
      },
      {
        key: "languages-3",
        icon: "images/logo-csharp.png",
        prof: 3,
        unlocked: true,
        alt: "C# OOP",
        prereqs: ["languages-2"],
      },
      {
        key: "languages-4",
        icon: "images/logo-java.png",
        prof: 2,
        unlocked: true,
        alt: "Java OOP",
      },
      {
        key: "languages-5",
        icon: "images/logo-Cplus.png",
        prof: 1,
        unlocked: true,
        alt: "C++ Systems",
      },
      {
        key: "languages-6",
        icon: null,
        prof: 4,
        unlocked: true,
        emoji: "🐚",
        alt: "Bash Scripting",
        prereqs: ["languages-1"],
      },
      {
        key: "languages-7",
        icon: null,
        prof: 2,
        unlocked: true,
        emoji: "🌀",
        alt: "TypeScript Basics",
        prereqs: ["web-6"],
      },
      {
        key: "languages-8",
        icon: null,
        prof: 0,
        unlocked: false,
        emoji: "🔍",
        alt: "GraphQL APIs",
        prereqs: ["web-8"],
      },
      {
        key: "languages-9",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "📚",
        alt: "Data Structures & Algorithms",
        prereqs: ["languages-2"],
      },
      {
        key: "languages-10",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "📐",
        alt: "OOP & Design Patterns",
        prereqs: ["languages-3"],
      },
    ],
    web: [
      {
        key: "web-1",
        icon: "images/logo-htmlcss.png",
        prof: 5,
        unlocked: true,
        alt: "HTML & CSS",
      },
      {
        key: "web-2",
        icon: "images/logo-javascript.png",
        prof: 4,
        unlocked: true,
        alt: "JavaScript for Web",
        prereqs: ["web-1"],
      },
      {
        key: "web-3",
        icon: "images/react-1-logo-png-transparent.png",
        prof: 3,
        unlocked: true,
        alt: "React",
        prereqs: ["web-6"],
      },
      {
        key: "web-4",
        icon: null,
        prof: 1,
        unlocked: true,
        emoji: "🚀",
        alt: "PWA",
        prereqs: ["web-3"],
      },
      {
        key: "web-5",
        icon: "images/logo-sql.png",
        prof: 2,
        unlocked: true,
        alt: "SQL & Databases",
      },
      {
        key: "web-6",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🧩",
        alt: "TypeScript",
        prereqs: ["web-2"],
      },
      {
        key: "web-7",
        icon: null,
        prof: 4,
        unlocked: true,
        emoji: "🟩",
        alt: "Node.js",
        prereqs: ["web-2"],
      },
      {
        key: "web-8",
        icon: null,
        prof: 0,
        unlocked: false,
        emoji: "🔺",
        alt: "GraphQL Basics",
        prereqs: ["web-7"],
      },
      {
        key: "web-9",
        icon: null,
        prof: 1,
        unlocked: true,
        emoji: "🗃️",
        alt: "NoSQL Databases",
        prereqs: ["web-5"],
      },
      {
        key: "web-10",
        icon: null,
        prof: 2,
        unlocked: true,
        emoji: "🛡️",
        alt: "Web Security Fundamentals",
        prereqs: ["web-2"],
      },
      {
        key: "web-11",
        icon: null,
        prof: 4,
        unlocked: true,
        emoji: "🧭",
        alt: "REST APIs (Express)",
        prereqs: ["web-7"],
      },
      {
        key: "web-12",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🧠",
        alt: "State Management",
        prereqs: ["web-3"],
      },
      {
        key: "web-13",
        icon: null,
        prof: 4,
        unlocked: true,
        emoji: "🔥",
        alt: "Firebase",
        prereqs: ["web-2"],
      },
      {
        key: "web-14",
        icon: null,
        prof: 4,
        unlocked: true,
        emoji: "⏭️",
        alt: "Next.js",
        prereqs: ["web-3", "web-6"],
      },
      {
        key: "web-15",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "☁️",
        alt: "Cloudflare Workers",
        prereqs: ["web-2"],
      },
      {
        key: "web-16",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🤖",
        alt: "Puppeteer",
        prereqs: ["web-7"],
      },
    ],
    tools: [
      {
        key: "tools-1",
        icon: "images/logo-github.png",
        prof: 3,
        unlocked: true,
        alt: "Git & GitHub",
      },
      {
        key: "tools-2",
        icon: null,
        prof: 2,
        unlocked: true,
        emoji: "🐧",
        alt: "Linux & Dev",
      },
      {
        key: "tools-3",
        icon: "images/logo-photoshop.png",
        prof: 5,
        unlocked: true,
        alt: "Photoshop",
      },
      {
        key: "tools-4",
        icon: "images/logo-blender.png",
        prof: 2,
        unlocked: true,
        alt: "Blender",
      },
      {
        key: "tools-5",
        icon: null,
        prof: 1,
        unlocked: true,
        emoji: "✅",
        alt: "QA & CI",
        prereqs: ["tools-1"],
      },
      {
        key: "tools-6",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🐳",
        alt: "Docker Basics",
        prereqs: ["tools-2"],
      },
      {
        key: "tools-7",
        icon: null,
        prof: 1,
        unlocked: true,
        emoji: "🔁",
        alt: "CI/CD Pipelines",
        prereqs: ["tools-5"],
      },
      {
        key: "tools-8",
        icon: null,
        prof: 2,
        unlocked: true,
        emoji: "🎨",
        alt: "Figma Basics",
      },
      {
        key: "tools-9",
        icon: null,
        prof: 4,
        unlocked: true,
        emoji: "🐳",
        alt: "Docker & Containerization",
        prereqs: ["tools-6"],
      },
      {
        key: "tools-10",
        icon: null,
        prof: 0,
        unlocked: false,
        emoji: "☸️",
        alt: "Kubernetes Basics",
        prereqs: ["tools-9"],
      },
      {
        key: "tools-11",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🧪",
        alt: "Unit Testing",
        prereqs: ["tools-5"],
      },
      {
        key: "tools-12",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🧭",
        alt: "Selenium",
        prereqs: ["languages-1", "tools-5"],
      },
      {
        key: "tools-13",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🛰️",
        alt: "Google Cloud Platform (GCP)",
        prereqs: ["tools-2", "tools-6"],
      },
    ],
    ai: [
      {
        key: "ai-3",
        icon: null,
        prof: 4,
        unlocked: true,
        emoji: "📊",
        alt: "NumPy",
        prereqs: ["languages-1"],
      },
      {
        key: "ai-1",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🧠",
        alt: "TensorFlow",
        prereqs: ["languages-1", "ai-3"],
      },
      {
        key: "ai-2",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "⚡",
        alt: "Flax & JAX",
        prereqs: ["languages-1", "ai-3"],
      },
      {
        key: "ai-4",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "🦙",
        alt: "Ollama",
        prereqs: ["languages-1"],
      },
      {
        key: "ai-5",
        icon: null,
        prof: 3,
        unlocked: true,
        emoji: "📚",
        alt: "LlamaIndex",
        prereqs: ["languages-1", "ai-1"],
      },
    ],
  };

  Object.freeze(nodes);
  global.perkNodes = nodes;

  if (typeof module !== "undefined" && module.exports) {
    module.exports = nodes;
  }
})(typeof window !== "undefined" ? window : globalThis);
